#!/bin/bash

# full path to node
NODE=/Users/ronnie/Unix/Node/bin/node

# server command
SERVER="$NODE fslogger.js"

# server URL
URL="http://127.0.0.1:8888"

# copy things to current directory
cp ../fslogger.js .

cat <<EOC > fslogger.conf
{
  "debug": false,
  "port": 8888,
  "logfile": "pbit.log",
  "timezoneStrings": { "300": "EST", "240": "EDT" },
  "logger": "CEF Logger"
}
EOC

# remove olg log file
/bin/rm -f pbit.log

$SERVER  2> /dev/null 1>server.log &
pid=$!
sleep 2

res=$(curl -s -I $URL | head -1 )
[[ "$res" == 'HTTP/1.1 200 OK'*  ]] || echo -n "Error on " && echo Test 1

res=$(curl -s -I ${URL}/test | head -1)
[[ "$res" == 'HTTP/1.1 200 OK'*  ]] || echo -n "Error on " && echo Test 2

res=$(curl -s -I -X HEAD ${URL} | head -1)
[[ "$res" == 'HTTP/1.1 200 OK'*  ]] || echo -n "Error on " && echo Test 3

res=$(curl -s -I -X POST ${URL} | head -1)
[[ "$res" == 'HTTP/1.1 200 OK'*  ]] || echo -n "Error on " && echo Test 4

res=$(curl -s -I -X PUT ${URL}/test | head -1)
[[ "$res" == 'HTTP/1.1 405'*  ]] || echo -n "Error on " && echo Test 5

# test big input
curl -s -X POST ${URL} -d@big.json > /dev/null
sleep 1
kill -0 $pid 2> /dev/null || echo -n "Error on " && echo Test 6

# test irrelevant JSON
curl -s -X POST ${URL} -d@other.json > /dev/null
sleep 1
kill -0 $pid 2> /dev/null || echo -n "Error on " && echo Test 7

# do something normal
curl -s -X POST ${URL} -d@doc.json > /dev/null
sleep 1
kill -0 $pid 2> /dev/null || echo -n "Error on " && echo Test 8

# do something else 
curl -s -X POST ${URL} -d@docA.json > /dev/null
sleep 1
kill -0 $pid 2> /dev/null || echo -n "Error on " && echo Test 9

# does pbit.log match?
pbitlogsum=$(md5 -q pbit.log)
if [ $pbitlogsum == '4b3a8a274c1cc7962bb26211e92112bd' ]
then 
  echo CEF log is as expected
else
  echo CEF log incorrect
fi

# does server.log match?
serverlogsum=$(awk -F'|' '{print $2}' server.log | md5 -q)
if [ $serverlogsum == '14eb2c18ff42c02c8606658ab4dde3f6' ]
then 
  echo Server log is as expected
else
  echo Server log incorrect
fi


# cleanup
kill $pid 2> /dev/null || echo "Failed to kill fslogger"
(sleep 1; /bin/rm -f fslogger.{js,conf})&


echo "No errors should have been emitted"
