#!/bin/bash

CLEANUP=$1
CLEANUP=${CLEANUP:-no}

# full path to node
NODE=/Users/ronnie/Unix/Node/bin/node

# server command
SERVER="$NODE fslogger.js"

# server URL
URL="http://127.0.0.1:8888"

# copy things to current directory
cp ../fslogger.js .

cat <<EOC > fslogger.conf
{
  "debug": false,
  "port": 8888,
  "logfile": "pbit.log",
  "timezoneStrings": { "300": "EST", "240": "EDT" },
  "logger": "CEF Logger"
}
EOC

# remove olg log file
/bin/rm -f pbit.log

$SERVER  2> /dev/null 1>server.log &
pid=$!
sleep 2

res=$(curl -s -I $URL | head -1 )
[[ "$res" == 'HTTP/1.1 200 OK'*  ]] || echo -n "Error on " && echo Test 1

res=$(curl -s -I ${URL}/test | head -1)
[[ "$res" == 'HTTP/1.1 200 OK'*  ]] || echo -n "Error on " && echo Test 2

res=$(curl -s -I -X HEAD ${URL} | head -1)
[[ "$res" == 'HTTP/1.1 200 OK'*  ]] || echo -n "Error on " && echo Test 3

res=$(curl -s -I -X POST ${URL} | head -1)
[[ "$res" == 'HTTP/1.1 200 OK'*  ]] || echo -n "Error on " && echo Test 4

res=$(curl -s -I -X PUT ${URL}/test | head -1)
[[ "$res" == 'HTTP/1.1 405'*  ]] || echo -n "Error on " && echo Test 5


# Loop over different JSON files
n=6
declare -a testJsons=(
  "live"
  "heart"
  "badA"
  "stateB"
  "stateA"
  "dereg"
  "registration"
  "other"
  "big"
)
for jf in "${testJsons[@]}"
do
  curl -s -X POST ${URL} -d@${jf}.json > /dev/null
  sleep 1
  kill -0 $pid 2> /dev/null || echo -n "Error on " && echo Test $n
  n=$((n+1))
done


# does pbit.log match?
pbitlogsum=$(md5 -q pbit.log)
if [ $pbitlogsum == '5f7a07670a477fa1580923ccecb33f5a' ]
then 
  echo CEF log is as expected
else
  echo CEF log incorrect
fi

# does server.log match?
serverlogsum=$(awk -F'|' '{print $2}' server.log | md5 -q)
if [ $serverlogsum == '541f8069e7d76892202186f9f78949e6' ]
then 
  echo Server log is as expected
else
  echo Server log incorrect
fi


# cleanup
kill $pid 2> /dev/null || echo "Failed to kill fslogger"
if [[ $CLEANUP == 'yes' ]]
then
    (sleep 1; /bin/rm -f fslogger.{js,conf})&
fi


echo "No errors should have been emitted"
