#!/bin/bash

#
#   INSTALL SCRIPT FOR fslogger
#

# set to yes to ignore the Nodejs check
ignore=$1

# alternative dir to install when testing
# testdir=$PWD/base/

NODE=/usr/bin/node
if [[ -z $ignore && ! -x $NODE ]]
then
  echo   "Node not at $NODE"
  printf 'You need to install Nodejs first.  Try\n'
  printf ' curl --silent --location https://rpm.nodesource.com/setup_8.x'
  printf ' | sudo bash -\n'
  printf ' yum install nodejs\n'
  exit 1
fi

# base directory to untar files
ROOT=${testdir:=/}

FB=${ROOT}opt/share
FH=$FB/fslogger


# create a user if needed
id -u fslogger > /dev/null 2>&1
if [[ $? -ne 0 ]]; then adduser -r fslogger; fi

# install fslogger related files
tar -xvf files.tgz -o -C $ROOT

# if there is no old conf file, create one
if [ ! -f $FH/fslogger.conf ]
then
  cp $FH/fslogger.conf.orig $FH/fslogger.conf
fi

# a place to save the DeepXi detections
if [ ! -d $FH/logs ]; then mkdir $FH/logs; fi

# make fslogger own some files
chown --recursive fslogger:fslogger $FH

# set the permissions for some files
chmod 664 ${FH}/fslogger.{conf,conf.orig,js}
chmod 775 ${FH}/logs

# schedule fslogger to start on reboot
chkconfig --level 2345 fslogger on
